name: custom action workflow

on:
  workflow_dispatch:
    inputs:
      project_name:
        description: Your project name
        required: true
      email:
        description: Your email id
        required: true

jobs:
  build:
    # The type of runner that the job will run on, this job will run on ubuntu machine
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
      REPO_NAME_WITH_OWNER: ${{ github.repository }}
      PROJECT_NAME: ${{ github.event.inputs.project_name }}

    steps:
      # Install Cookie cutter
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Installing cookiecutter
        id: install_cookie_cutter
        run: pip3 install cookiecutter
      # Run cookie cutter
      - name: Running cookiecutter
        id: running_cookie_cutter
        run: |
          cookiecutter gh:$REPO_NAME_WITH_OWNER --no-input \
            project_name="$PROJECT_NAME" \
            email="${{ github.event.inputs.email }}"
          echo "Moving the generated template to root directory"
          mv $PROJECT_NAME/* /home/runner/work/$REPO_NAME/$REPO_NAME/
          echo "cleaning up..."
          echo "removing template folder"
          rm -rf \{\{\ cookiecutter.project_name\ \}\}
          echo "removing generated template folder"
          rm -rf $PROJECT_NAME
          echo "removing template workflows"
          rm .github/workflows/template.yml
          echo "removing cookiecutter.json file"
          rm cookiecutter.json
      - name: Commit generated template changes
        uses: EndBug/add-and-commit@v9
        with:
            add: .
            message: "Library initiated with template"
            default_author: github_actions
